### ISSUE TITLE
dbutils.library.installPyPI deprecation

### ISSUE THREAD

**Issue by michaelcarrico-8451** [benthurber-8451/example_camid_ob_new_pattern#2]
This way of installing packages will be deprecated soon so would consider switching this to:

`%pip install epp_metrics==1.0.8b6`

https://github.com/benthurber-8451/example_camid_ob_new_pattern/blob/3418605f3b410a6ba28d79130f58f2b962580613/src/id2_section_resource_split.py#L38

**Comment by benthurber-8451** [comment]
Done
