### ISSUE TITLE
EppMetrics import

### ISSUE THREAD

**Issue by michaelcarrico-8451** [benthurber-8451/example_camid_ob_new_pattern#3]
Minor stylistic note, but you don't need to reference epp_metrics_api here and can instead do:

`from epp_metrics import EppMetrics`

https://github.com/benthurber-8451/example_camid_ob_new_pattern/blob/3418605f3b410a6ba28d79130f58f2b962580613/src/id2_section_resource_split.py#L55

**Comment by benthurber-8451** [comment]
Done
